### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ilyar** [everscale-org/docs#13]
- [ ] docs.ton.dev
  - [ ] RUN https://docs.ton.dev/86757ecb2/v/0/n/65d8af
  - [ ] WRITE https://docs.ton.dev/86757ecb2/n/9475af
  - [ ] API/SDK https://docs.ton.dev/86757ecb2/n/700297
  - [ ] DECENTRALIZE https://docs.ton.dev/86757ecb2/n/27bf32
    - [ ] DECENTRALIZE
    - [ ] TONOS-CLI
    - [ ] EXCHANGE
 - [ ] RELEASES https://docs.ton.dev/86757ecb2/n/82bab3
 - [ ] ABOUT TON OS https://docs.ton.dev/86757ecb2/n/231b77
- [ ] everos.dev
- [ ] docs.tonalliance.org
- [ ] tonlabs.notion.site
- [ ] Wallet
  - [ ] Ever Surf
    - [ ] For developers https://tonlabs.notion.site/For-developers-f347bd4095f74c9d9e2bd313c666905d
  - [ ] Everspace
    - [ ] How to implement on your web site authentication using Everspace wallet (rebranding from Oberton) https://github.com/itgoldio/everscale-auth-everspace 
    - [ ] How to implement on your web site authentication using Surf https://github.com/itgoldio/everscale-auth-debot
    - [ ] Оur submission to standardize TrueNFT format https://github.com/itgoldio/everscale-tnft  https://github.com/itgoldio/everscale-tnft-interfaces

**Comment by Futurizt** [comment]
Names have changed.

**Comment by elasticLove1** [comment]
https://tonlabs.gitbook.io/ton-sdk/
https://tonlabs.gitbook.io/evernode-platform/

**Comment by ilyar** [comment]
split https://github.com/everscale-org/docs/issues/21
