### ISSUE TITLE
Docs Roadmap

### ISSUE THREAD

**Issue by ilyar** [everscale-org/docs#21]
- [ ] https://aerial-ulna-579.notion.site/Everscale-solidity-dfcb9b950e11414baee1408709e82fe0
- [ ] move TIP form forum https://forum.freeton.org/c/development/tip/5
- [ ] docs.ton.dev
  - [ ] RUN https://docs.ton.dev/86757ecb2/v/0/n/65d8af
  - [ ] WRITE https://docs.ton.dev/86757ecb2/n/9475af
  - [ ] API/SDK https://docs.ton.dev/86757ecb2/n/700297
  - [ ] DECENTRALIZE https://docs.ton.dev/86757ecb2/n/27bf32
    - [x] DECENTRALIZE
    - [ ] TONOS-CLI
    - [ ] EXCHANGE
 - [ ] RELEASES https://docs.ton.dev/86757ecb2/n/82bab3
 - [ ] ABOUT TON OS https://docs.ton.dev/86757ecb2/n/231b77
- [ ] everos.dev
- [ ] docs.tonalliance.org
- [ ] tonlabs.notion.site
- [ ] https://tonlabs.gitbook.io/flex/
- [ ] Wallet
  - [ ] Ever Surf
    - [ ] For developers https://tonlabs.notion.site/For-developers-f347bd4095f74c9d9e2bd313c666905d
  - [ ] Everspace
    - [ ] How to implement on your web site authentication using Everspace wallet (rebranding from Oberton) https://github.com/itgoldio/everscale-auth-everspace 
    - [ ] How to implement on your web site authentication using Surf https://github.com/itgoldio/everscale-auth-debot
    - [ ] Оur submission to standardize TrueNFT format https://github.com/itgoldio/everscale-tnft  https://github.com/itgoldio/everscale-tnft-interfaces
